
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.kubesnoop.io
  resources:
  - lifecycles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubesnoop.io
  resources:
  - lifecycles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kubesnoop.io
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - update
  - watch
